name: Publish alpine-demo to dockerhub
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: samarpanda/alpine-demo
      DOCKER_IMAGE_TAG: 1.0.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker Image
        working-directory: alpine-demo
        run: |
          pwd
          docker build -t $DOCKER_IMAGE_NAME:latest -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG -f Dockerfile .

      - name: Log in to DockerHub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Publish Docker Image (latest)
        run: |
          docker push $DOCKER_IMAGE_NAME:latest

      - name: Publish Docker Image ($DOCKER_IMAGE_TAG)
        run: |
          docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG