name: Publish alpine-demo image to dockerhub
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build docker Image
        working-directory: alpine-demo
        run: |
          pwd
          docker build -t samarpanda/alpine-demo:1.0.0 -f Dockerfile .
      - name: Publish Docker Image
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push samarpanda/alpine-demo:1.0.0
          docker push samarpanda/alpine-demo:latest