name: Publish v14-node-pm2 to dockerhub
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: samarpanda/node-pm2
      DOCKER_IMAGE_TAG: 14.21.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker Image
        working-directory: node-pm2
        run: |
          pwd
          docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG -f Dockerfile .

      - name: Log in to DockerHub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin --quiet

      - name: Publish Docker Image ($DOCKER_IMAGE_TAG)
        run: |
          docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
